
ipynb-filters: [nbdev_filter]

project:
  type: website
  output-dir: _docs
  preview:
    port: 3000
    browser: false

format:
  html:
    theme: darkly
    # css: styles.css
    toc: true

website:
  title: "my-notes"
  twitter-card: true
  reader-mode: true
  repo-branch: master
  repo-url: https://github.com/muellerzr/my-notes
  repo-actions: [issue]
  navbar:
    background: primary
    search: true
    left:
      - text: Home
        file: index.ipynb
    right:
      - icon: github
        href: https://github.com/muellerzr/my-notes/
  sidebar:
    style: "floating"

metadata-files: 
  - sidebar.yml
